<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DAlogo</name>
   <tag></tag>
   <elementGuidId>6f5b9eb4-e434-425b-908c-0fedeccabed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f135dba-0929-4f06-8416-faeb29100175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Demo/assets/DALogo-9168ca15.svg</value>
      <webElementGuid>b57806c6-5f48-4f23-ad00-e3799a4d33f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>9f5ef171-0246-4a22-8e46-e52f5cde3aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ihgnxF hZSsZq</value>
      <webElementGuid>45aec1e6-7add-4d74-acc7-789263614aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex items-center h-[100vh]&quot;]/form[@class=&quot;sc-bBeLUv bKjCus&quot;]/div[@class=&quot;sc-fvtFIe hDdokS&quot;]/img[@class=&quot;sc-ihgnxF hZSsZq&quot;]</value>
      <webElementGuid>6c18cdce-214f-4c89-91ab-30fad2190b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/img</value>
      <webElementGuid>6581633e-1aef-473d-a35c-4caca2886a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>0564ce8b-4a96-488f-88e9-3232112571f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>98b0164d-c34c-432b-b133-94fb925d3e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      <webElementGuid>8243e473-acb3-463a-ab79-61d518654a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
