<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DAlogo</name>
   <tag></tag>
   <elementGuidId>6f5b9eb4-e434-425b-908c-0fedeccabed5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.sc-ihgnxF.hZSsZq</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9b740f07-7e2d-4b3b-8b39-a7f59d323189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Demo/assets/DALogo-9168ca15.svg</value>
      <webElementGuid>05434d8e-5fae-411a-92c0-ade6f13caa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>02a98099-3d6c-4652-b9a0-469dc529c12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ihgnxF hZSsZq</value>
      <webElementGuid>b5dd67ac-0910-43f4-9551-e5aa86fed179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex items-center h-[100vh]&quot;]/form[@class=&quot;sc-bBeLUv bKjCus&quot;]/div[@class=&quot;sc-fvtFIe hDdokS&quot;]/img[@class=&quot;sc-ihgnxF hZSsZq&quot;]</value>
      <webElementGuid>1267a194-3c98-49ed-be68-db22f4823b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/img</value>
      <webElementGuid>e3e316de-2264-4f0d-ac10-cc838bf7d482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>828e348c-0a55-4d16-9574-18aa3f32dadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8e77b56f-2edd-482d-bbe3-6ca1c61c6039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      <webElementGuid>ddab8e26-11ff-48c9-baf6-f9ca3747326c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
