<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DAlogo</name>
   <tag></tag>
   <elementGuidId>6f5b9eb4-e434-425b-908c-0fedeccabed5</elementGuidId>
   <imagePath>C:\Users\Home\Desktop\DALogo-9168ca15.svg</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.sc-ihgnxF.hZSsZq</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\Home\Desktop\DALogo-9168ca15.svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>364207e1-a253-4d58-904c-7337f11afd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Demo/assets/DALogo-9168ca15.svg</value>
      <webElementGuid>3a38563e-4df3-4188-b3e6-a501b2a16265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>98c51ad2-0c62-4eb9-b228-5f429868fa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ihgnxF hZSsZq</value>
      <webElementGuid>e7a01513-0704-44d7-ac53-4cb8defc1422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex items-center h-[100vh]&quot;]/form[@class=&quot;sc-bBeLUv bKjCus&quot;]/div[@class=&quot;sc-fvtFIe hDdokS&quot;]/img[@class=&quot;sc-ihgnxF hZSsZq&quot;]</value>
      <webElementGuid>3971c12c-5446-4ceb-8bfd-e60efcc30139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/img</value>
      <webElementGuid>f229123b-1077-42ba-be96-1ea33a25ed08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>54b06aeb-95c8-4cf8-93bd-d8200b03e903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e3395bfe-38da-4bb6-a610-8a21eeaebe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Demo/assets/DALogo-9168ca15.svg' and @alt = 'logo']</value>
      <webElementGuid>edc4c64b-8200-4b3d-b5e8-d628d0a418c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
